 version: '0.1'

 services:
   web:
    image: btelecomweb:0.1
    build: .
    command: python manage.py runserver 0.0.0.0:80
    ports:
      - "80:80"
    volumes:
      - '/opt/sites/btelecom'
      - './media/produtos/:/opt/sites/btelecom/media/produtos/'